# Generated by Django 4.0.4 on 2022-05-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_image1_product_image2_product_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, choices=[('hot', 'hot'), ('new', 'new'), ('sale', 'sale')], max_length=50, null=True),
        ),
    ]
