# Generated by Django 4.0.4 on 2022-05-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
