# Generated by Django 4.0.4 on 2022-05-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingadress',
            old_name='city',
            new_name='adress2',
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='state',
            new_name='country',
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='pyment',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='save_information',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='subscribe',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='terms_conditions',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
