# Generated by Django 4.0.4 on 2022-05-16 23:30

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_rename_city_shippingadress_adress2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingadress',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='shippingadress',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingadress',
            name='pyment',
            field=models.BooleanField(default=False),
        ),
    ]
