# Generated by Django 4.0.4 on 2022-05-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_blog_blog_post_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_post',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
