# Generated by Django 4.0.4 on 2022-05-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_blog_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, choices=[('red', 're'), ('green', 'gr'), ('blue', 'bl'), ('yellow', 'ye'), ('orange', 'or'), ('pink', 'pi')], max_length=50, null=True),
        ),
    ]
