# Generated by Django 4.0.4 on 2022-05-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_product_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, choices=[('re', 'red'), ('gr', 'green'), ('bl', 'blue'), ('ye', 'yellow'), ('or', 'orange'), ('pi', 'pink')], max_length=50, null=True),
        ),
    ]
