# Generated by Django 4.0.4 on 2022-05-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_alter_product_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('re', 'red'), ('gr', 'green'), ('bl', 'blue'), ('ye', 'yellow'), ('or', 'orange'), ('pi', 'pink')], max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, max_length=50, null=True, to='ecommerce.colors'),
        ),
    ]
