# Generated by Django 4.0.4 on 2022-05-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_colors_remove_product_colors_product_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productimage',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
