# Generated by Django 4.0.4 on 2022-06-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_colors_product_colors_and_more'),
        ('accounts', '0007_rename_addres1_userprofile_adress1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fav_products',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
