# Generated by Django 4.0.4 on 2022-06-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_complated_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pyment_method',
            field=models.CharField(choices=[('paypal', 'paypal'), ('cod', 'cod'), ('credit', 'credit'), ('bank', 'bank')], max_length=100),
        ),
    ]
