# Generated by Django 4.0.4 on 2022-06-10 22:06

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_payment_pyment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expired',
            field=creditcards.models.CardExpiryField(default=1.0),
        ),
    ]
