# Generated by Django 4.0.4 on 2022-05-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productimage',
            field=models.ImageField(blank=True, null=True, upload_to='media/%y/%m/%d'),
        ),
    ]
