# Generated by Django 4.0.4 on 2022-05-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(blank=True, choices=[('small', 'small'), ('larg', 'larg'), ('medium', 'medium'), ('xl', 'xl'), ('2xl', '2xl'), ('big', 'big')], null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='colors',
            name='name',
            field=models.CharField(blank=True, choices=[('red', 'red'), ('green', 'green'), ('blue', 'blue'), ('yellow', 'yellow'), ('orange', 'orange'), ('pink', 'pink')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, max_length=50, to='products.colors'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, max_length=50, to='products.size'),
        ),
    ]
